### ISSUE TITLE
lidar won't process

### ISSUE THREAD

**Issue by MyronBedford** [chadrockey/TGC-Designer-Tools#112]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tgc_gui.py", line 521, in runLidar
  File "lidar_map_api.py", line 247, in generate_lidar_previews
  File "site-packages\numpy\core\numeric.py", line 309, in full
MemoryError
The lidar loaded the attempt before but I had forgotten to put one of the files in. I t didn't work after that. There isn't any difference between the files I had and this one.

**Comment by chadrockey** [comment]
It’s implying your computer is out of memory, you could check with system manager or try a more powerful computer.
