### ISSUE TITLE
Tool won't process lidar

### ISSUE THREAD

**Issue by MyronBedford** [chadrockey/TGC-Designer-Tools#114]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tgc_gui.py", line 521, in runLidar
  File "lidar_map_api.py", line 247, in generate_lidar_previews
  File "site-packages\numpy\core\numeric.py", line 309, in full
MemoryError
When I process lidar it runs all of the files through and then this shows up.

**Comment by chadrockey** [comment]
Computer likely out of RAM or memory.  Try using fewer lidar files or be sure that your lidar files are all next to each other and not very far apart like on separate sides of a city.
