### ISSUE TITLE
tool won't generate heightmap.

### ISSUE THREAD

**Issue by MyronBedford** [chadrockey/TGC-Designer-Tools#123]
Previously I was getting an error that said my computer didn't have enough power. I now have a new computer and it's giving me the same error. What is going on?
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tgc_gui.py", line 521, in runLidar
  File "lidar_map_api.py", line 247, in generate_lidar_previews
  File "site-packages\numpy\core\numeric.py", line 309, in full
MemoryError

**Comment by MyronBedford** [comment]
It will process the EPSG and the lidar but when it gets to the point of generating the heightmap the error comes up.

**Comment by chadrockey** [comment]
This error indicates your computer ran out of memory (RAM), you’ll need to use fewer LiDAR tiles or try a different computer.
