### ISSUE TITLE
.course file not exporting

### ISSUE THREAD

**Issue by Paddyjk19** [chadrockey/TGC-Designer-Tools#13]
Hi Chad,

Finished all of the processes listed in you tutorial but when I go to export the .course file back to the created folder I click save and when I got to copy it into 2k folder it just isn't there.

Please can you look at this?

Thanks

Patrick

**Comment by KalCormier** [comment]
I'm having same problem. Can't get .Course file to export. Getting this exception:

Exception in Tkinter callback
Traceback (most recent call last):
File "tkinter\__init__.py", line 1705, in __call__
File "tgc_gui.py", line 130, in importCourseAction
File "tgc_tools.py", line 89, in unpack_course_file
File "c:\users\chad\appdata\local\programs\python\pytho n37\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u200b' in position 255: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
File "tkinter\__init__.py", line 1705, in __call__
File "tgc_gui.py", line 155, in exportCourseAction
File "tgc_tools.py", line 181, in set_course_metadata_name
File "tgc_tools.py", line 151, in get_metadata_json
File "json\__init__.py", line 348, in loads
File "json\decoder.py", line 337, in decode
File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by chadrockey** [comment]
Sorry guys, didn't have notifications on for this repo.

@KalCormier your issue was fixed in this commit:
https://github.com/chadrockey/TGC-Designer-Tools/commit/3ec70628608c6d1532857f2e9fdcd9bbcab9cc6b

@Paddyjk19 let me know if you're still having issues.
