### ISSUE TITLE
Unable to process Lidar due to mapquest request issue

### ISSUE THREAD

**Issue by zalmighty1** [chadrockey/TGC-Designer-Tools#131]
found EPSG direct from EPSG.io

tool processes Lidar but upon mapquest retrieval, I receive this message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tgc_gui.py", line 521, in runLidar
  File "lidar_map_api.py", line 340, in generate_lidar_previews
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>

any thoughts??

**Comment by zalmighty1** [comment]
im using 3.3
