### ISSUE TITLE
The tool can't download the OSM

### ISSUE THREAD

**Issue by MyronBedford** [chadrockey/TGC-Designer-Tools#134]
For some reason, the OSM isn't downloading when processing lidar. The course view will pop up for you to select the amount of lidar you want and the OSM won't be overlayed. I did get an error once that said that the OSM can't be downloaded but I'm not getting that error anymore. I'll go through the process and then the course preview will have nothing. 

The one error I am getting is this:
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tgc_gui.py", line 547, in generateCourseFromLidar
  File "tgc_image_terrain.py", line 246, in generate_course
  File "tgc_image_terrain.py", line 119, in get_lidar_trees
  File "GeoPointCloud.py", line 230, in projToCV2
  File "GeoPointCloud.py", line 198, in enuToCV2
ValueError: cannot convert float NaN to integer
Now I don't know whether this is a completely different issue, (I like to use the trees from the lidar because they're more accurate.)
or whether it's part of the OSM gongshow but this also appears sometimes. While it's creating the course preview.

**Comment by chadrockey** [comment]
@MyronBedford check the areas of the course, it looks like there might be a waypoint without a coordinate.

says you’re getting a NaN in a calculation, so it’s likely a point like 0,0 snuck in

**Comment by MyronBedford** [comment]
How and where would I do that?

**Comment by chadrockey** [comment]
I would recommend exporting the course from the main OSM website as xml and
looking at the geo points and the ways for the course and seeing if you can
identify any that are weird or different or uninitialized somehow.

It can be pretty labor intensive, please list the course here as well.

**Comment by MyronBedford** [comment]
The course is Kelowna Golf and country club

**Comment by MyronBedford** [comment]
I tried going back through and checking every individual point and line. Would there be a problem with points that aren't disconnected from each other?
When I'm loading Lidar it gives me this before the outline.

Adding golf features to lidar data
OpenStreetMap Overpass query: (node(nan,132.9671996917034,nan,133.25691928702742);way(nan,132.9671996917034,nan,133.25691928702742););out;
OpenStreetMap servers are too busy right now.  Try running this tool later.
OpenStreetMap download failed.  You won't see helpful OSM outlines or drawings on your preview or mask.
Mapquest Image URL Request: https://www.mapquestapi.com/staticmap/v5/map?key=MAPQUEST_API_KEY&scalebar=true&format=png&center=nan,133.11171883879825&type=hyb&zoom=16&size=1500,963
Could not get sat preview: HTTP Error 401: Unauthorized

**Comment by MyronBedford** [comment]
The OSM won't download even now. It keeps coming up with this error:
OpenStreetMap Overpass query: (node(nan,132.9671996917034,nan,133.25691928702742);way(nan,132.9671996917034,nan,133.25691928702742););out;
OpenStreetMap servers are too busy right now. Try running this tool later.
OpenStreetMap download failed. You won't see helpful OSM outlines or drawings on your preview or mask.
Mapquest Image URL Request: https://www.mapquestapi.com/staticmap/v5/map?key=MAPQUEST_API_KEY&scalebar=true&format=png&center=nan,133.11171883879825&type=hyb&zoom=16&size=1500,963
Could not get sat preview: HTTP Error 401: Unauthorized

Even when the OSM servers are obviously not busy, I can't get into them when they are.
