### ISSUE TITLE
Stuck at "filling missing data in heightmap"

### ISSUE THREAD

**Issue by Clacardinals** [chadrockey/TGC-Designer-Tools#136]
When importing heightmap and osm into course i keep getting stuck when it says "Fillinf missing data in heightmap" I know it is supposed to take a while but have waited up to 30 minutes with nothing. When i open up the gui i get the following message:

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tgc_gui.py", line 547, in generateCourseFromLidar
  File "tgc_image_terrain.py", line 197, in generate_course
  File "infill_image.py", line 96, in infill_image_scipy
  File "infill_image.py", line 8, in apply_mask
IndexError: boolean index did not match indexed array along dimension 0; dimension is 656 but corresponding boolean dimension is 657

Any one have any idea what i am doing wrong?

**Comment by chadrockey** [comment]
@Clacardinals sorry that's not stuck, that's a crash.  Could you send some screenshots of the preview when you draw the box around the course etc?

**Comment by Clacardinals** [comment]
![Select Course Boundaries 12_21_2024 18_04_06](https://github.com/user-attachments/assets/afaef03f-43f5-43c5-a82c-f8955bc9f9d6)

Pretty sure i have messed something up at this point. New to this so sorry for the confusion.

**Comment by chadrockey** [comment]
Looks like quite a bit of the course is missing? (the large black box)

It will be tricky, but you'll need to find which lidar "tile" file you're missing.

**Comment by Clacardinals** [comment]
I have found what tile was missing. Got OSM to import on the map but still only show one lidar on the left with the white box on the right. Ive plugged every EPSG in the state I am in and still cant get both to pop up with a map. Everytime I get to the last tab I get the same error message pop up. I have a feeling its to do with the lidar/EPSG number but i cant seem to find the correct EPSG anywhere.

**Comment by Clacardinals** [comment]
I figured it out. The way I was editing the photo was messing it up for some reason. I tried it without highlighting anything in red and it went through. Not sure why that was an issue but im glad it is done with.
