### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by mfvaughan** [chadrockey/TGC-Designer-Tools#53]
Receiving following error after generating and editing mask.png and trying to "Select and Import Heightmap and OSM into Course", any ideas? 

`Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "tgc_gui.py", line 547, in generateCourseFromLidar
  File "tgc_image_terrain.py", line 197, in generate_course
  File "infill_image.py", line 58, in infill_image_scipy
IndexError: index 437 is out of bounds for axis 1 with size 437`

**Comment by mfvaughan** [comment]
Woops, I had cropped the image. That was the issue.
